version: '3'

services:
  django:
    build: ./api
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - SECRET_KEY=%mdpwimuwy8nfb3q5=zbz_hkwujdp2$a#g6=8@bvb(^5!x_3cz
      - DJANGO_SETTINGS_MODULE=api.settings.dev
    restart: always
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
